package main

// Generated by https://quicktype.io

// Results - TheMetalDetektor Output
type Results struct {
	Matches           []Match       `json:"matches"`
	MatchCount        int64         `json:"match_count"`
	ShopCount         int64         `json:"shop_count"`
	UnresponsiveShops []interface{} `json:"unresponsive_shops"`
	SlowestShop       SlowestShop   `json:"slowest_shop"`
}

// Match - Individual Results for search
type Match struct {
	URL     string `json:"url"`
	Listing string `json:"listing"`
	Price   string `json:"price"`
	Shop    string `json:"shop"`
}

// SlowestShop - Shop that took the longest time to return results
type SlowestShop struct {
	Shop string  `json:"shop"`
	Time float64 `json:"time"`
}
